### ISSUE TITLE
Is 'vis ' a third-party package or a python file that not shared in this project ? 

### ISSUE THREAD

**Issue by bobby20180331** [OllieBoyne/smal-fitter#2]
Runtime error:
ModuleNotFoundError: No module named 'vis'

from vis import stack_as_batch, try_mkdir

Is 'vis ' a third-party package  keras.vis  or a python file that not shared in this project ? 
Thanks!

**Comment by OllieBoyne** [comment]
Hi,

I have pushed a change to fix this issue - some file renaming had not been updated.

**Comment by bobby20180331** [comment]
Thanks! Now it works well.I can get the smbld model now.
