### ISSUE TITLE
should load_toy_verts([21, 22, 24, 24, 25])  be  [21, 22, 23, 24, 25]? 

### ISSUE THREAD

**Issue by bobby20180331** [OllieBoyne/smal-fitter#3]
HI,
When  We combine 13 dogs parameters  with 5 dogs from smal. should be [21, 22, 23, 24, 25]? [2dogs (21,22),1fox (23),1wolf(24),1hyena(25)]
However ,seems that your smbld model use [21, 22, 24, 24, 25],Why?
  
in model.py
     # data = np.load("static_fits_output/smbld_params_13_deform.npz")
    # unity_verts = data["verts"]
    #
    # toy_verts = load_toy_verts([21, 22, 24, 24, 25])
    #
    # all_verts = np.concatenate([unity_verts, toy_verts])
    #
    # save_new_model(all_verts)

**Comment by OllieBoyne** [comment]
Hi,

I believe you are correct, that is an error. I have removed that commented part of code to avoid confusion.
